java.sql.SQLDataException: Value '10' is outside of valid range for type java.lang.Byte
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:92)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1423)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getByte(ResultSetImpl.java:710)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getByte(ResultSetImpl.java:716)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getByte(HikariProxyResultSet.java)
	at org.starloco.locos.database.dynamics.data.RuneData.load(RuneData.java:22)
	at org.starloco.locos.game.world.World.createWorld(World.java:405)
	at org.starloco.locos.kernel.Main.start(Main.java:116)
	at org.starloco.locos.kernel.Main.main(Main.java:101)
Caused by: com.mysql.cj.exceptions.NumberOutOfRange: Value '10' is outside of valid range for type java.lang.Byte
	at com.mysql.cj.result.ByteValueFactory.createFromBytes(ByteValueFactory.java:113)
	at com.mysql.cj.result.ByteValueFactory.createFromBytes(ByteValueFactory.java:46)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:143)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:135)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243)
	at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1306)
	... 7 more
